services:
  next-app:
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test1.rule=Host(`test1.detnet.com`) && PathPrefix(`/test`)"
      - "traefik.http.routers.test1.entrypoints=websecure"
      - "traefik.http.routers.test1.tls.certResolver=letsencrypt"
      - "traefik.http.routers.test1.middlewares=my-app-strip"
      - "traefik.http.middlewares.my-app-strip.stripPrefix.prefixes=/test"
      - "traefik.http.services.test1.loadbalancer.server.port=3000"
networks:
  dokploy-network:
    external: true